# 0205 JAVA

### java program 단위

- class: 단일 상속만 가능
- enum: 열거타입, (public) static+final (상수), 열거된 상수를 표현하는 프로그램 단위
- interface: 다중 상속을 위한 프로그램 단위



### class와 enum 비교

``` java
class week extends {
    public static final char MON='월'
    public static final char TUE='화'
    public static final char WED='수'
}
```

``` java
public enum week{ //week는 enum의 이름
    MON, TUE, WED
}
```

if 다른 class에서 enum을 사용하고 싶다면?

``` java
class Test {
    main (){
        system.out.println(week.MON)
    }
}
```

-> MON이 출력됨

내가 정해준 그 이름으로 그냥 값을 찾음 (똑같은 이름에 똑같은 값을 가졌다?-? 이름과 똑같은 값을 가졌다)

즉,

``` java
package test.enum_;

public enum Week {
	MON,화,수; // 하나하나의 객체가 만들어진 것
}

은 Week라는 객체를 만든 것
(어떤 이름으로 주소를 저장하는진 모르겠지만 '월'의 주소를 Week 안에 객체로 저장되어있다)
```

``` java
package test.enum_;

public class Test {
	public static void main(String[] args) {
		Week o1=Week.MON; //enum= 객체를 생성해서 o1에 MON의 주소를 저장하겠다
        System.out.println(o1); //toString이 overriding... (나중에 다시 설명)
	}

}

```



### Interface

> 모든 method가 abstract 이어야 함
>
> (반드시 하위에서 구현해야하고 규격이 맞아야 함)

``` java
public interface Flyer {
    
}
```

``` java
class Bird extends Animal implements Flyer{ //animal은 직접 상속중, fly라는 interface i상속중
    
}

class Superman extends Human implements Flyer{ //
    
}

class Airplane extends Vehicle implements Flyer{
    
}
```

- 직접 상속은 실선, implements는 UML에서 점선으로 표현

- Type이 하나 확장 된 것 (bird 객체는 bird, animal, object, flyer type 총 4가지 type으로 사용 가능!)

- 위 3가지 class는 모두 똑같은 이름?의 method를 가져야 함 ex. 모두 fly(){} 사용

  - 만약 이미 flight로 했으면?

  - fly () {

    flight(); } 로 flight 호출

  ``` java
  class Test {
      main
      Bird b=new Bird();
      Superman s=new Superman();
      Airplane a=new Airplane();
  }
  ```

  

  ``` java
  class Show {
      public void airShow (Flyer f){
          f.fly(); //fly 사용하는 애들은 다 abstract해서 반드시 객체,, 있음..?..
      }
  }
  ```

- interface는 보통 ~하는 애 할 때 많이 사용

- 근데 이렇게 flyer f로 사용하면 bird를 flyer 타입으로 바라보겠다는 것

  - Flyer로 보면 animal과 bird가 shadow effect

  - Flyer만 사용해서 바라보겠다는 것

  - | object --------- (옆에 Flyer) |
    | ----------------------------- |
    | Animal                        |
    | Bird                          |

    (Object는 shadow effect 받지 않음. Flyer로 바라봐도 object의 method는 다 갖는다)



> 예시

``` java
package my.fly;

public class Show { //utility class
	
	public void airShow(Flyer f) { //Fly 할 수 있는 애들만 들어와!
		f.fly();
	}

}
```



``` java
package my.fly;

public class Bird extends Animal implements Flyer{
	
	@Override
	public void eat() { //새가 eat하는 것 설정 가능
		System.out.println("벌레를 잡아 먹고 산다");
	}
	
	@Override
	public void fly() {
		System.out.println("날개로 난다");
	}
}

```

``` java
package my.fly;

public class Superman extends Human implements Flyer{ //Human을 상속했으므로 밥, 직립보행 이미 포함됨
	@Override
	public void eat() {
		super.eat(); // 밥을 먹는다 (Human이 가진 eat 이니까 super로 출력!)
		System.out.println("빵도 먹는다");
	}
	
	@Override
	public void fly () {
		System.out.println("망토를 휘날리며 난다");
	}

}

```

``` java
package my.fly;

public class Airplane extends Vehicle implements Flyer{

	public void flight() {
		int distance=transfer(10,1000); //method 호출 (필요한 값 넣기)
		System.out.println(distance+"거리만큼 엔진을 가동해서 난다");
	}
	
	@Override
	public void fly() {
		flight();
	}
}

```

``` java
package my.fly;

public class Test {

	public static void main(String[] args) {
		
		Animal ani=new Animal();
		ani.eat(); // 내용이 안 나온다
		
		Flyer b=new Bird();
		Flyer s=new Superman();
		Airplane a=new Airplane(); //Flyer도, 그냥 그대로 부르는 것도 가능
		
		Show show=new Show(); //Class이름 참조변수이름 = new ~~
		show.airShow(b);
		show.airShow(s);
		show.airShow(a);
		// show.airShow("java"); -> error남. 왜? air show 할 수 있는 애들은 flyer만! (show를 호출했는데 show는 flyer만 받음)
		
	}

}

```



# CH 7

```java
package test.inheritance;

public class People {
	private String name, ssn;

	public People(String name, String ssn) {
		super();
		this.name = name;
		this.ssn = ssn;
	}
	

}

class Student extends People{
	Student(){
		super(); // super에 아무것도 받지 않는 생성자가 없기 때문에 오류. String 값 2개를 가져야 super를 사용할 수 있음
	}
}

```



super에 argument를 받지 않는 생성자가 없기 때문에 오류가 난다

따라서

``` java
package test.inheritance;

public class People {
	private String name, ssn;

	public People() {
		super();
		// TODO Auto-generated constructor stub
        // 이렇게 아무것도 받지 않는 생성자를 만들어줘야 오류를 해결할 수 있다
	}



	public People(String name, String ssn) {
		super();
		this.name = name;
		this.ssn = ssn;
	}
	

}

class Student extends People{
	Student(){
		super(); // 지금은 아무것도 받지 않는 super 생성자가 있어서 오류 안 남
	}
}

```



# Modifier

>  abstract: 객체 생성 불가, 상속으로만 사용해야 한다

- class, method 앞에만 붙일 수 있음 (data 불가)
  - class: 객체 생성 불가 (상속으로만 써야한다)
  - method: 구현되지 않았음

```java
package test.shape;

public class Shape {
	public void area () {//메소드 정의
		//구현 -> 현재는 도형이 정해진게 아니라 구현할 수 없음
        // overriding해서 shape의 area method를 circle, rectangle, triangle class에서 area method를 구체화 하여 사용할 수 있도록
	}

}
```

얘를 다르게 표현하면 (얘는 Shape.s=new Shape를 쓸 수 없어 ㅠㅠ 안에 내용이 없거든!)

``` java
package test.shape;

public abstract class Shape { //access 뒤에 usage modifier
	abstract public void area (); // 기대하지마 구현된 거 없어! 객체 생성 못 해 상속만 해야돼! usage 뒤에 access modifier 

}

```

앞에 지정자가 있고 ();면 정의, 지정자 없고 (); 하면 정의된 게 없다는 뜻

- abstract 의 경우 access랑 usage 맘대로 바꿔서 써줘도 됨! 근데 보통 access usage 순으로 씀

- **abstract이 한개라도 있으면 그 class 는 무조건 abstract**
- abstract 선언은 안했지만 그럼에도 상속으로만 쓰게 하고 싶으면 그 class에 abstract 선언할 수 있음



- Shape 객체를 생성하는 건 안되지만 하위 class의 객체를 shape type으로 선언하는 건 가능함

``` java
package test.shape;

public class Test {

	public static void main(String[] args) {
		
		Shape s=new Circle(); // 상속된 class를 골라서 사용 (직접 shape 객체 생성은 못하니까 하위 class를 이용해서 객체 만들었음) 이걸 실행하면 Circle의 area를 결과로 낼 수 있다!
        // 만약 Circle 대신 triangle을 쓰면 triangle을 사용해서 삼각형의 area 도출 됨
		s.area(); //오버라이딩 된 메서드 호출
        
    }
}
```

​	(Circle은 Shape 상속중)

​	이 경우엔 원의 넓이를 결과값으로 낼 수 있다

- 즉, abstract 선언된 자신을 쓰지 말고 하위의 상속 받은 class를 객체화 해서 사용해라, 만약 사용하고 싶은게 없다면 직접 만들어라

​	



다시 설명

Animal의 eat method를 Human, Bird, Superman이 overriding 하는 중일 때,



``` java
package my.fly;

public class Animal {
	
	public void eat() {
		
	}

}
```

얘는 그냥 template인데 (for overriding)

``` java
package my.fly;

public class Test {

	public static void main(String[] args) {
		
		Animal ani=new Animal();
		ani.eat(); // 내용이 안 나온다
    }
}

```

내용을 기대하고 객체를 만들어서 실행하면 당연히 아무런 결과 안 나옴

따라서, template에 내용을 기대하지도 말아라! 라고 표현하기 위해서

``` java
package my.fly;

public abstract class Animal {
	
	public abstract void eat() ;
		
	}
```

으로 설정해서 abstract class인 Animal을 객체화 하지 않게 만들어주고, (상속만 사용하도록)

``` java
package my.fly;

public class Test {

	public static void main(String[] args) {
		
		Animal ani=new Animal(); // -> 이거 객체화 못 해! 컴파일 에러 남
		ani.eat(); //
    }
}
```

객체 생성 할 수 없어서 만들어진 컴파일 에러를 수정하기 위해 상속을 이용해야 한다

Animal을 상속중 & eat method를 overriding 중인 class는 Human, Bird, Superman

또는 직접 Animal을 상속하고, method를 overriding 중인 class를 만들어준다

``` java
package my.fly;

public class Test {

	public static void main(String[] args) {
		
		Animal ani=new Human();
        //Human을 객체화해서 그 주소를 ani에 저장할게, 그리고 얘를 Animal 부터 볼게 (Animal이라고 가정하고 볼게)
        //원래 그러면 하위 class인 Human 부분이 shadow effect 처리 되지만 지금 Human은 eat method를 overriding 중이기 때문에 가려지지 않고 호출이 가능하다.
		ani.eat();
    }
}

```

으로 고쳐주면 Human의 eat method가 호출되어 그 결과값이 결과로 도출된다.

즉, Animal class를 상속 중인 Human class를 객체화하여 eat method를 사용하는 건 가능하지만, Animal class를 직접 객체화 해서 사용하는 건 불가능하다



## 숙제

> is a 관계 외에 확장할 수 있는 것 찾아보기 (필기 참고)



## 교재 코드



``` java
package test.interface_;

public interface RemoteControl {
	//상수
	int MAX_VOLUME = 10;
	int MIN_VOLUME = 0;
	
	//추상 메소드
	void turnOn();
	void turnOff();
	void setVolume(int volume);
	
	//디폴트 메소드
	default void setMute(boolean mute) {
		if(mute) {
			System.out.println("무음 처리합니다.");
		} else {
			System.out.println("무음 해제합니다.");
		}
	}
	
	//정적 메소드
	static void changeBattery() {
		System.out.println("건전지를 교환합니다.");
	}
}
```



``` java
package test.interface_;

public class Television implements RemoteControl {
	//필드
	private int volume;
	
	//turnOn() 추상 메소드의 실체 메소드
	public void turnOn() {
		System.out.println("TV를 켭니다.");
	}	
	//turnOff() 추상 메소드의 실체 메소드
	public void turnOff() {
		System.out.println("TV를 끕니다.");
	}
	//setVolume() 추상 메소드의 실체 메소드
	public void setVolume(int volume) {
		if(volume>RemoteControl.MAX_VOLUME) {
			this.volume = RemoteControl.MAX_VOLUME;
		} else if(volume<RemoteControl.MIN_VOLUME) {
			this.volume = RemoteControl.MIN_VOLUME;
		} else {
			this.volume = volume;
		}
		System.out.println("현재 TV 볼륨: " + volume);
	}
}
```



``` java
package test.interface_;

public class Audio implements RemoteControl {
	//필드
	private int volume;
	
	//turnOn() 추상 메소드의 실체 메소드
	public void turnOn() {
		System.out.println("Audio를 켭니다.");
	}	
	//turnOff() 추상 메소드의 실체 메소드
	public void turnOff() {
		System.out.println("Audio를 끕니다.");
	}
	//setVolume() 추상 메소드의 실체 메소드
	public void setVolume(int volume) {
		if(volume>RemoteControl.MAX_VOLUME) {
			this.volume = RemoteControl.MAX_VOLUME;
		} else if(volume<RemoteControl.MIN_VOLUME) {
			this.volume = RemoteControl.MIN_VOLUME;
		} else {
			this.volume = volume;
		}
		System.out.println("현재 Audio 볼륨: " + volume);
	}
}
```

``` java
package test.interface_;

public class RemoteControlExample {
	public static void main(String[] args) {
		RemoteControl rc = null;
		
		rc = new Television();
		rc.turnOn();
        rc.setMute(true); //true일 때 무음처리
		rc.turnOff();
		
		rc = new Audio();
		rc.turnOn();
		rc.turnOff();
        
        RemoteControl.changeBattery(); //특정 개체가 아니라 모든 곳에 적용
        // 따라서 rc.하면 안 뜨고 RemoteControl.해야 뜬다
	}
}
```



# Ch.10

## Exception (예외)

> 프로그래밍 오류를 잡고 실행을 계속할 수 있는 기법

``` java
package test.exception;

public class Test {

	public static void main(String[] args) {
		int x=100;
		int y=0;
		System.out.println(x/y);
		System.out.println("아주 중요한 일 시작"); //이 밑에서부터 아주 중요한 일이 일어난다고 가정하자
		
	}

}
```

를 돌리면 Exception in thread "main" java.lang.ArithmeticException: / by zero
	at test.exception.Test.main(Test.java:8) 가 출력된다

위에 사소한 거 때문에 밑에 중요한 걸 실행 못 한다니...!

미리 감지하지 못한 에러를 감수하고 JVM이 계속 돌아가게 하기 위해선 어떻게 해야 할까?

**try를 넣는다**

``` java
package test.exception;

public class Test {

	public static void main(String[] args) {
		try {
		int x=100;
		int y=0;
		System.out.println(x/y);
		} catch(ArithmeticException e) {
			
		}
		System.out.println("아주 중요한 일 시작");
		
	}

}

--> 아주 중요한 일 시작 (출력됨)
```

이를 예외처리라고 한다

try block 내에서 예외처리 날 수 있는 exception을 catch에 넣어주면 JVM이 중간에 끝나지 않고 끝까지 수행할 수 있다

``` java
package test.exception;

public class Test {

	public static void main(String[] args) {
		try {
		int x=100;
		int y=0;
		System.out.println(x/y);
		} catch(ArithmeticException e) {
			System.out.println(e.getMessage());
		}
		System.out.println("아주 중요한 일 시작"); //이 밑에서부터 아주 중요한 일이 일어난다고 가정하자
		
	}

}

--> / by zero
아주 중요한 일 시작 출력됨
```

 

여기서 / by zero는 0으로 나눠서 오류 났다는 것

에러가 안 나면 catch 수행 안 하고 점프



- 이번엔 중첩 catch를 해보자

``` java
package test.exception;

public class Test {

	public static void main(String[] args) {
		try {
		int x=100;
		int y=Integer.parseInt(args[0]);
		System.out.println(x/y);
		}catch(ArithmeticException e) {
			System.out.println(e.getMessage());
		}catch(NumberFormatException e) {
			System.out.println(e.getMessage());
		}
		System.out.println("아주 중요한 일 시작"); //이 밑에서부터 아주 중요한 일이 일어난다고 가정하자
		
	}

}

--> For input string: "삼"
아주 중요한 일 시작

   (Run configuration에서 삼 넣었었음)
```

``` java
package test.exception;

public class Test {

	public static void main(String[] args) {
		try {
		int x=100;
		int y=Integer.parseInt(args[0]);
		System.out.println(x/y);
		} catch(ArithmeticException e) {
			System.out.println(e.getMessage());
		}catch(NumberFormatException e) {
			System.out.println(e.getMessage());
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println(e.getMessage());
		}
		System.out.println("아주 중요한 일 시작"); //이 밑에서부터 아주 중요한 일이 일어난다고 가정하자
		
	}

}

--> 0
아주 중요한 일 시작
 출력
```

근데 알아보기 힘드니까

``` java
package test.exception;

public class Test {

	public static void main(String[] args) {
		try {
		int x=100;
		int y=Integer.parseInt(args[0]);
		System.out.println(x/y);
		} catch(ArithmeticException e) {
			System.out.println("영으로 나누지 마세요");
		}catch(NumberFormatException e) {
			System.out.println("숫자로 바꿀 수 없는 입력입니다");
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("숫자를 입력하세요");
		}
		System.out.println("아주 중요한 일 시작"); //이 밑에서부터 아주 중요한 일이 일어난다고 가정하자
		
	}

}

--> 숫자를 입력하세요
아주 중요한 일 시작
(오류가 뭔지 알 수 있음)
```

근데 이렇게 하면 catch block에 있는 오류만 잡을 수 있는데...?ㅠㅠ 어떤 오류가 날지 몰라서 catch 하기 힘듦

그럴땐 catch(Exception e)를 쓰면 된다

- 예시: run configuration에서 args에 2를 넣고 apply and run을 하자

``` java
package test.exception;

public class Test {

	public static void main(String[] args) {
		try {
		int x=100;
		args[0]=null; //받아 들인 2를 다시 null로 바꿨고 null을 trim 하면 exception이 발생한다
		int y=Integer.parseInt(args[0].trim());
		System.out.println(x/y);
		} catch(ArithmeticException e) {
			System.out.println("영으로 나누지 마세요");
		}catch(NumberFormatException e) {
			System.out.println("숫자로 바꿀 수 없는 입력입니다");
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("숫자를 입력하세요");
		}catch(Exception e) {
			System.out.println("어떤 exception이 발생");
		}
		System.out.println("아주 중요한 일 시작"); //이 밑에서부터 아주 중요한 일이 일어난다고 가정하자 (위에서 오류가 나도 수행되어야 한다)
		
	}

}

-->어떤 exception이 발생
아주 중요한 일 시작

    
```

- 받아 들인 2를 다시 null로 바꿨고 null을 trim 하면 exception이 발생한다
- 근데 이걸 catch할 catch block이 없어서 Exception e로 들어가서 "어떤 exception이 발생"이 출력된 것
- exception으로 하면 이미 '어떤 오류'라고 걸리기 때문에 하위 exception들을 위에 두고 맨 밑에 exception을 넣어야 한다



## Throw, Throws

> Throw : Exception 발생 전에 Exception 상황이 벌어질 수 있는지 사전에 확인하고, 그 안에서 exception을 발생시킨다.
>
> Throws: 발생한 Exception을 던져준다

- RuntimeException: 실행을 해봐야 오류가 발생했는지 알 수 있는 예외들. 실행 전에는 체크가 불가능함 (unchecked)
- 나머지 Exception들은 컴파일러가 개발 시점에 미리 알려주기 때문에 대비를 할 수 있음 (Checked exception) ex. IOException
- Runtime Exception을 미리 체크할 수 있게 만들고 싶으면?
  - MyException을 runtime 말고 exception의 하위 개체로 만들어 준다 (미리 check 할 수 있도록)
  - 그리고 exception 발생 직전 상황에 if로 exception을 만들어서 exception을 발생 시키고 throw 해줌
  - 그럼 throw 된 쪽에서 오류가 발생해서 대비가 가능함

``` java
package test.exception2;

public class Calculator {

	public int divide(int x, int y) throws Exception {
		int z=0;
		if (y==0) {
			throw new Exception(); //throw=발생하다 throw는 Exception이랑 밖에 사용 안 됨 (Exception을 발생시키다)
		}
			z=x/y;
		return z;
	}

}

```

이걸 만들고 나면

``` java
package test.exception2;

public class Test {

	public static void main(String[] args) {
		
		Calculator c=new  ㅊㅊㅊㅊㅊㅊㅊㅊㅊㅊㅊㅊㅊㅊㅊㅊㅊㅊㅊ  Calculator();
		int result=c.divide(100, 0); --> 여기에서 exception handling 안됐다고 컴파일 오류가 뜸
		System.out.println(result);
		
		System.out.println("아주 중요한 일 시작");
	}

}

```

- 왜 컴파일 오류가 뜰까?
  - Exception이 일어날 수 있기 때문에 개발하는 시점에 미리 대비할 수 있도록
- main method에서는 throws exception **절대** 하면 안됨!! Try Catch 해야 한다
- 그럼 얘네를 컴파일 오류 없애려면,

``` java
package test.exception2;

public class Test {

	public static void main(String[] args) {
		
		Calculator c=new Calculator();
		int result=0; //의미 없는 값이라도 넣어줘야 한다
		try {
			result = c.divide(100, 0);
		} catch (Exception e) {
			system.out.println(e.getMessage();)
		}
		System.out.println(result);
		
		System.out.println("아주 중요한 일 시작");
	}

}

-> 
```

- 왜 e.printStackTrace(); 대신 system.out.println(e.getMessage();) 를 쓸까?
  - e.printStackTrace(); 얘는 trace message를 그대로 출력하기 때문에 보안에 취약함
  - throw에서 받은 message를 그대로 출력하는게 프로그램상 더 낫다
  - e를 사용하면 throw new Exception("메시지")에서 message를 참조 할 수 있음



더 발전된 코딩을 위해서는 MyException class를 만들어서 수정해주자

(메시지를 전달하기 위해서!)

``` java
package test.exception2;

public class MyException extends Exception{

	public MyException(String message) {
		super(message);
	}

}

```

이걸 만들어줬으니 다른 애들도 Exception을 MyException으로 바꿔주자

``` java
package test.exception2;

public class Calculator {

	public int divide(int x, int y) throws MyException {
		int z=0;
		if (y==0) {
			throw new MyException("y를 0으로 입력하지 마세요"); //throw=발생하다 throw는 Exception이랑 밖에 사용 안 됨 (Exception을 발생시키다)
		} //MyException은 message를 받기 때문에 ""로 채워넣어줘야함
			z=x/y;
		return z;
	}

}

```

``` java
package test.exception2;

public class Test {

	public static void main(String[] args) {
		
		Calculator c=new Calculator();
		int result=0; //의미 없는 값이라도 넣어줘야 한다
		try {
			result = c.divide(100, 0);
		} catch (MyException e) {
			system.out.println(e.getMessage();)
		}
		System.out.println(result);
		
		System.out.println("아주 중요한 일 시작");
	}

} 
```

``` java
package test.exception2;

public class Calculator {

	public int divide(int x, int y) throws MyException {
		int z=0;
		if (y==0) { //exception을 발생시켜서 던지기 (밑에 throw 있음)
			throw new MyException("y를 0으로 입력하지 마세요"); //throw=발생하다 throw는 Exception이랑 밖에 사용 안 됨 (Exception을 발생시키다)
		} //MyException은 message를 받기 때문에 맞는 타입의 값을 꼭 채워넣어줘야함
			z=x/y;
		return z;
	}

}
```

- throw -> 오류 발생하면 나, 즉 MyException 객체의 주소값을 호출한 곳으로 던져줌
- 이 비상 상황에 대한 대응이 try / catch (return값을 받지도 못하구)
- MyException 들어온거 e라고 받을게 -> e는 MyException의 주소가 있음
- e 참조해서 MyException의 getMessage 하면 literal pool에 있는 "y를 0으로 입력하지 마세요"를 가져오게 된다



### MyException 다시 설명

> 오류가 발생할 수 있는 상황에서 미리 오류를 발생시켜서 throws 할 수 있도록 객체화 시킨 것

- 나누기 할 때가 아니라, 나누기 전에 if(y==0)을 넣어서 미리 exception을 발생시킴

``` java
package test.exception2;

public class Calculator {

	public int divide(int x, int y) throws MyException {
		int z=0;
		if (y==0) {
			throw new MyException("y를 0으로 입력하지 마세요");
		}
			z=x/y;
		return z;
	}

}

```

- 그냥 new 하면 throws 할 수가 없어서 throw로 미리 exception을 발생 시켜서 throws 해서 나를 호출한 쪽에 에러를 전달할 수 있도록 한다

- 그럼 날 호출한 쪽은 try catch를 할 기회를 얻게 된다 -> 미리 대비할 수 있음

``` java
package test.exception2;

public class Test {

	public static void main(String[] args) {
		
		Calculator c=new Calculator();
		int result=0;
		try {
			result = c.divide(100, 0);
		} catch (MyException e) {
			System.out.println(e.getMessage());
		}
		System.out.println(result);
		
		System.out.println("아주 중요한 일 시작");
	}

}

```

- 이렇게!-!
- 